### ISSUE TITLE
Media features that accept min/max prefixes

### ISSUE THREAD

**Issue by ryentzer** [benfrain/rwd#1]
First, great book. I'm currently reading to increase my experience with the current state of CSS/HTML.

In chapter two under the title "What can media queries test for?" you state "All the preceding features, with the exception of scan and grid, can be prefixed with min or max to create ranges."

But after considering "orientation" that didn't make sense so I checked the spec and indeed it doesn't accept min/max prefixes.

> 4.5. orientation
> Value: portrait | landscape
> Applies to: bitmap media types
> Accepts min/max prefixes: no

**Comment by benfrain** [comment]
Hi, yes, you are correct of course. I'll endeavour to correct in the next edition. 

Glad the book is proving useful :)
